Feature/enable reductions stack
ivan-pavlov/rvwgsoc pull request #8
Opened 2018-07-01 22:23 UTC by ivan-pavlov

This PR adds new `add_reduction` function.
I looked closer into how VW [stacks reductions](https://github.com/JohnLangford/vowpal_wabbit/blob/a9bba04b13bb87878c6d24ef212c220a7cb4822a/vowpalwabbit/parse_args.cc#L1089-L1150) and decided to add this functionality as it sounds like a natural way for VW. 

You can work with diffrent reductions like that:
```
test_vwmodel <-  vwsetup(dir = "./", model = "mdl.vw",
                         reduction = "ect", num_classes=3) %>%
    add_reduction(reduction = "boosting", num_learners=10)
```

In this way, you can add multiple reductions to  VW model.

2018-07-01 22:25 UTC, eddelbuettel commented
What is a 'reduction' ? Is there VW documentation for us to read up on?

2018-07-01 22:32 UTC, ivan-pavlov commented
This is how VW calls different learning modes:
https://github.com/JohnLangford/vowpal_wabbit/wiki/Command-line-arguments#learning-algorithm--reduction-options

But I think now, maybe word "reductions" is not general enough.

2018-07-01 22:35 UTC, eddelbuettel commented
Nice.  A demo file might illustrate this well.

2018-07-01 22:45 UTC, ivan-pavlov commented
I have an example on how to use this in `demo/example_1.R` file, but I am also planning to add more examples with different learning modes and reductions.

2018-07-01 23:04 UTC, coatless requested changes

2018-07-01 23:04 UTC, coatless commented on tests/testthat/test-vwsetup.R
> +params_str = paste(" --passes 1 --bit_precision 18 --holdout_period 10",
Should be `paste0(...)` instead of `paste(... ,sep = "")`

2018-07-01 23:04 UTC, coatless commented on tests/testthat/test-vwsetup.R
> +  lda_test_model$params_str = paste(" --passes 1 --bit_precision 18",
Ditto on `paste0(...)`

2018-07-01 23:04 UTC, coatless commented on tests/testthat/test-vwsetup.R
> +  custom_test_model$params_str <- paste(" --passes 10 --bit_precision 18",
Ditto on `paste0(...)`

2018-07-02 13:17 UTC, eddelbuettel approved these changes
Looks good to me (have not run it yet though).

2018-07-02 13:17 UTC, eddelbuettel commented on DESCRIPTION
>  Date: 2018-05-22
Try to remember to update the date with the version.  (Ie next time you do.)

2018-07-02 14:37 UTC, coatless approved these changes

2018-07-02 14:39 UTC, merged